_target_: lightning.pytorch.Trainer

# Basic settings
max_epochs: 100
accelerator: auto
devices: auto
precision: 16-mixed

# Training optimization
gradient_clip_val: 1.0
gradient_clip_algorithm: norm
accumulate_grad_batches: 1

# Validation
val_check_interval: 1.0
check_val_every_n_epoch: 1
num_sanity_val_steps: 2

# Logging
log_every_n_steps: 50
enable_progress_bar: true
enable_model_summary: true

# Checkpointing
enable_checkpointing: true
default_root_dir: null

# Performance
deterministic: false
benchmark: true
sync_batchnorm: false

# Detection
detect_anomaly: false
track_grad_norm: -1

# Memory optimization
max_memory: null
limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
limit_predict_batches: null

# Profiling
profiler: null

# Fast development run
fast_dev_run: false
overfit_batches: 0.0

# Reload dataloaders
reload_dataloaders_every_n_epochs: 0

# Strategy
strategy: auto

# Callbacks (will be overridden by callbacks config)
callbacks: null

# Loggers (will be overridden by logger config)  
logger: null
