name: astrobio-gen-cuda12.4
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.11
  
  # CUDA and GPU support for RunPod A500
  - cudatoolkit=12.4
  - nvidia-ml-py3
  
  # Core PyTorch ecosystem (compatible with RunPod A500)
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pytorch-lightning=2.4.0
  
  # Core numerical computing
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.2.2
  - xarray=2024.2.0
  
  # Scientific data handling
  - netcdf4=1.6.5
  - h5py=3.11.0
  - zarr=2.16.1
  - dask=2024.2.1
  
  # Astronomy
  - astropy=6.0.1
  - astroquery=0.4.7
  
  # Graph neural networks
  - pytorch-geometric=2.5.3
  
  # Web and async
  - aiohttp=3.9.5
  - fastapi=0.104.1
  - uvicorn=0.24.0
  
  # Development tools
  - black=24.3.0
  - isort=5.13.2
  - ruff=0.3.7
  - pre-commit=3.7.1
  
  # Jupyter and visualization
  - jupyter=1.0.0
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - plotly=5.19.0
  
  # System utilities
  - psutil=5.9.8
  - tqdm=4.66.4
  - pyyaml=6.0.1
  
  # Pip packages not available in conda
  - pip
  - pip:
    # Enhanced ML for production
    - transformers>=4.35.0
    - peft>=0.7.0
    - accelerate>=0.25.0
    - bitsandbytes>=0.41.0
    - sentence-transformers>=2.2.2
    - optuna>=3.4.0
    - "ray[tune]>=2.8.0"
    
    # Specialized scientific packages
    - cobra>=0.29.1
    - optlang>=1.7.0
    - rdkit-pypi==2022.9.5
    - atmos==0.2.6
    - pint>=0.23
    - pyproj>=3.6
    - specutils>=1.13
    - lightkurve>=2.4
    - pysynphot>=2.0
    - pysiaf>=0.19
    
    # Graph neural network extensions
    - torch-scatter>=2.1.0
    - torch-sparse>=0.6.18
    
    # Classical ML
    - scikit-learn>=1.4.0
    - umap-learn>=0.5.0
    - lightgbm>=4.3.0
    
    # Web scraping and HTTP
    - requests>=2.31.0
    - beautifulsoup4>=4.12.0
    - lxml>=4.9.0
    - urllib3>=2.0.0
    
    # Cloud and storage
    - boto3>=1.34.0
    - botocore>=1.34.0
    - s3fs>=2024.10.0
    
    # Production deployment
    - kafka-python>=2.0.2
    - redis>=5.0.0
    - kubernetes>=29.0.0
    - prometheus-client>=0.19.0
    - websockets>=12.0
    
    # Model optimization
    - onnxruntime>=1.16.0
    - tritonclient[all]>=2.40.0
    
    # Async and concurrency
    - asyncpg>=0.29.0
    - aiofiles>=23.2.1
    - schedule>=1.2.0
    
    # Security
    - cryptography>=41.0.0
    
    # Data version control
    - dvc>=3.35.0
    - "dvc[gs]>=3.35.0"
    
    # Monitoring and observability
    - jaeger-client>=4.8.0
    - grafana-api>=1.0.3
    - psycopg2-binary>=2.9.0
    
    # Additional scientific dependencies
    - networkx==3.2.1
    - sympy>=1.12
    - shap>=0.42.0
    - graphviz>=0.20.0
    - sqlalchemy>=1.4.0
    - gputil>=1.4.0
    
    # Async AWS support
    - aiobotocore>=2.15.2
